import type { MarketFilter } from "./filters";
import type { MarketRegionId } from "./markets";

/** Compact country rows used to build the app region catalog. */
export type CountrySeed = {
  id: string;
  label: string;
  /** ISO 4217; remapped onto AppCurrency when unsupported for display. */
  currency: string;
  marketRegion: MarketRegionId;
  primaryMarkets?: readonly MarketFilter[];
};

const AMERICAS: MarketFilter[] = ["NASDAQ", "NYSE"];
const EUROPE: MarketFilter[] = ["Euronext", "LSE"];
const APAC: MarketFilter[] = ["HKEX", "Nikkei"];

/**
 * UN member states + Taiwan, Hong Kong, and EU.
 * Alphabetical by English short name.
 */
export const COUNTRY_SEEDS: readonly CountrySeed[] = [
  { id: "af", label: "Afghanistan", currency: "USD", marketRegion: "apac", primaryMarkets: APAC },
  { id: "al", label: "Albania", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "dz", label: "Algeria", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ad", label: "Andorra", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ao", label: "Angola", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ag", label: "Antigua and Barbuda", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "ar", label: "Argentina", currency: "USD", marketRegion: "americas", primaryMarkets: ["B3", "NYSE"] },
  { id: "am", label: "Armenia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "au", label: "Australia", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "at", label: "Austria", currency: "EUR", marketRegion: "europe", primaryMarkets: ["XETRA", "Euronext"] },
  { id: "az", label: "Azerbaijan", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "bs", label: "Bahamas", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "bh", label: "Bahrain", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "bd", label: "Bangladesh", currency: "USD", marketRegion: "apac", primaryMarkets: ["BSE", "SGX"] },
  { id: "bb", label: "Barbados", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "by", label: "Belarus", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "be", label: "Belgium", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "bz", label: "Belize", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "bj", label: "Benin", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "bt", label: "Bhutan", currency: "INR", marketRegion: "apac", primaryMarkets: ["BSE"] },
  { id: "bo", label: "Bolivia", currency: "USD", marketRegion: "americas", primaryMarkets: ["B3"] },
  { id: "ba", label: "Bosnia and Herzegovina", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "bw", label: "Botswana", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "br", label: "Brazil", currency: "BRL", marketRegion: "americas", primaryMarkets: ["B3"] },
  { id: "bn", label: "Brunei", currency: "SGD", marketRegion: "apac", primaryMarkets: ["SGX"] },
  { id: "bg", label: "Bulgaria", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "bf", label: "Burkina Faso", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "bi", label: "Burundi", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "cv", label: "Cabo Verde", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "kh", label: "Cambodia", currency: "USD", marketRegion: "apac", primaryMarkets: ["SGX", "HKEX"] },
  { id: "cm", label: "Cameroon", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ca", label: "Canada", currency: "CAD", marketRegion: "americas", primaryMarkets: ["TSX"] },
  { id: "cf", label: "Central African Republic", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "td", label: "Chad", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "cl", label: "Chile", currency: "USD", marketRegion: "americas", primaryMarkets: ["B3", "NYSE"] },
  { id: "cn", label: "China", currency: "CNY", marketRegion: "apac", primaryMarkets: ["SSE", "HKEX"] },
  { id: "co", label: "Colombia", currency: "USD", marketRegion: "americas", primaryMarkets: ["B3", "NYSE"] },
  { id: "km", label: "Comoros", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "cg", label: "Congo", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "cd", label: "Congo (DRC)", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "cr", label: "Costa Rica", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "ci", label: "Côte d'Ivoire", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "hr", label: "Croatia", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "cu", label: "Cuba", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "cy", label: "Cyprus", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "cz", label: "Czechia", currency: "EUR", marketRegion: "europe", primaryMarkets: ["XETRA"] },
  { id: "dk", label: "Denmark", currency: "DKK", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "dj", label: "Djibouti", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "dm", label: "Dominica", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "do", label: "Dominican Republic", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "ec", label: "Ecuador", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "eg", label: "Egypt", currency: "USD", marketRegion: "europe", primaryMarkets: ["TADAWUL", "LSE"] },
  { id: "sv", label: "El Salvador", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "gq", label: "Equatorial Guinea", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "er", label: "Eritrea", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ee", label: "Estonia", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "sz", label: "Eswatini", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "et", label: "Ethiopia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "eu", label: "European Union", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext", "XETRA"] },
  { id: "fj", label: "Fiji", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "fi", label: "Finland", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "fr", label: "France", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "ga", label: "Gabon", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "gm", label: "Gambia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ge", label: "Georgia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "de", label: "Germany", currency: "EUR", marketRegion: "europe", primaryMarkets: ["XETRA"] },
  { id: "gh", label: "Ghana", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "gr", label: "Greece", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "gd", label: "Grenada", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "gt", label: "Guatemala", currency: "USD", marketRegion: "americas", primaryMarkets: ["BMV"] },
  { id: "gn", label: "Guinea", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "gw", label: "Guinea-Bissau", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "gy", label: "Guyana", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "ht", label: "Haiti", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "hn", label: "Honduras", currency: "USD", marketRegion: "americas", primaryMarkets: ["BMV"] },
  { id: "hk", label: "Hong Kong", currency: "HKD", marketRegion: "apac", primaryMarkets: ["HKEX"] },
  { id: "hu", label: "Hungary", currency: "EUR", marketRegion: "europe", primaryMarkets: ["XETRA"] },
  { id: "is", label: "Iceland", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "in", label: "India", currency: "INR", marketRegion: "apac", primaryMarkets: ["BSE"] },
  { id: "id", label: "Indonesia", currency: "IDR", marketRegion: "apac", primaryMarkets: ["SGX", "HKEX"] },
  { id: "ir", label: "Iran", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "iq", label: "Iraq", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "ie", label: "Ireland", currency: "EUR", marketRegion: "europe", primaryMarkets: ["LSE", "Euronext"] },
  { id: "il", label: "Israel", currency: "USD", marketRegion: "europe", primaryMarkets: ["LSE", "NASDAQ"] },
  { id: "it", label: "Italy", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "jm", label: "Jamaica", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "jp", label: "Japan", currency: "JPY", marketRegion: "apac", primaryMarkets: ["Nikkei"] },
  { id: "jo", label: "Jordan", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "kz", label: "Kazakhstan", currency: "USD", marketRegion: "apac", primaryMarkets: APAC },
  { id: "ke", label: "Kenya", currency: "USD", marketRegion: "europe", primaryMarkets: ["LSE"] },
  { id: "ki", label: "Kiribati", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "kw", label: "Kuwait", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "kg", label: "Kyrgyzstan", currency: "USD", marketRegion: "apac", primaryMarkets: APAC },
  { id: "la", label: "Laos", currency: "USD", marketRegion: "apac", primaryMarkets: ["SGX", "HKEX"] },
  { id: "lv", label: "Latvia", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "lb", label: "Lebanon", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ls", label: "Lesotho", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "lr", label: "Liberia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ly", label: "Libya", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "li", label: "Liechtenstein", currency: "CHF", marketRegion: "europe", primaryMarkets: ["SIX"] },
  { id: "lt", label: "Lithuania", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "lu", label: "Luxembourg", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "mo", label: "Macao", currency: "HKD", marketRegion: "apac", primaryMarkets: ["HKEX"] },
  { id: "mg", label: "Madagascar", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "mw", label: "Malawi", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "my", label: "Malaysia", currency: "MYR", marketRegion: "apac", primaryMarkets: ["SGX", "HKEX"] },
  { id: "mv", label: "Maldives", currency: "USD", marketRegion: "apac", primaryMarkets: ["BSE", "SGX"] },
  { id: "ml", label: "Mali", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "mt", label: "Malta", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "mh", label: "Marshall Islands", currency: "USD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "mr", label: "Mauritania", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "mu", label: "Mauritius", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "mx", label: "Mexico", currency: "MXN", marketRegion: "americas", primaryMarkets: ["BMV"] },
  { id: "fm", label: "Micronesia", currency: "USD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "md", label: "Moldova", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "mc", label: "Monaco", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "mn", label: "Mongolia", currency: "USD", marketRegion: "apac", primaryMarkets: ["HKEX", "SSE"] },
  { id: "me", label: "Montenegro", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ma", label: "Morocco", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "mz", label: "Mozambique", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "mm", label: "Myanmar", currency: "USD", marketRegion: "apac", primaryMarkets: ["SGX", "HKEX"] },
  { id: "na", label: "Namibia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "nr", label: "Nauru", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "np", label: "Nepal", currency: "INR", marketRegion: "apac", primaryMarkets: ["BSE"] },
  { id: "nl", label: "Netherlands", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "nz", label: "New Zealand", currency: "NZD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "ni", label: "Nicaragua", currency: "USD", marketRegion: "americas", primaryMarkets: ["BMV"] },
  { id: "ne", label: "Niger", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ng", label: "Nigeria", currency: "USD", marketRegion: "europe", primaryMarkets: ["LSE"] },
  { id: "kp", label: "North Korea", currency: "USD", marketRegion: "apac", primaryMarkets: ["KRX"] },
  { id: "mk", label: "North Macedonia", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "no", label: "Norway", currency: "NOK", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "om", label: "Oman", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "pk", label: "Pakistan", currency: "USD", marketRegion: "apac", primaryMarkets: ["BSE", "HKEX"] },
  { id: "pw", label: "Palau", currency: "USD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "ps", label: "Palestine", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "pa", label: "Panama", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "pg", label: "Papua New Guinea", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "py", label: "Paraguay", currency: "USD", marketRegion: "americas", primaryMarkets: ["B3"] },
  { id: "pe", label: "Peru", currency: "USD", marketRegion: "americas", primaryMarkets: ["B3"] },
  { id: "ph", label: "Philippines", currency: "PHP", marketRegion: "apac", primaryMarkets: ["SGX", "HKEX"] },
  { id: "pl", label: "Poland", currency: "PLN", marketRegion: "europe", primaryMarkets: ["XETRA"] },
  { id: "pt", label: "Portugal", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "qa", label: "Qatar", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "ro", label: "Romania", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ru", label: "Russia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "rw", label: "Rwanda", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "kn", label: "Saint Kitts and Nevis", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "lc", label: "Saint Lucia", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "vc", label: "Saint Vincent and the Grenadines", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "ws", label: "Samoa", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "sm", label: "San Marino", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "st", label: "Sao Tome and Principe", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "sa", label: "Saudi Arabia", currency: "SAR", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "sn", label: "Senegal", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "rs", label: "Serbia", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "sc", label: "Seychelles", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "sl", label: "Sierra Leone", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "sg", label: "Singapore", currency: "SGD", marketRegion: "apac", primaryMarkets: ["SGX"] },
  { id: "sk", label: "Slovakia", currency: "EUR", marketRegion: "europe", primaryMarkets: ["XETRA"] },
  { id: "si", label: "Slovenia", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "sb", label: "Solomon Islands", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "so", label: "Somalia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "za", label: "South Africa", currency: "ZAR", marketRegion: "europe", primaryMarkets: ["LSE"] },
  { id: "kr", label: "South Korea", currency: "KRW", marketRegion: "apac", primaryMarkets: ["KRX"] },
  { id: "ss", label: "South Sudan", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "es", label: "Spain", currency: "EUR", marketRegion: "europe", primaryMarkets: ["Euronext"] },
  { id: "lk", label: "Sri Lanka", currency: "USD", marketRegion: "apac", primaryMarkets: ["BSE", "SGX"] },
  { id: "sd", label: "Sudan", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "sr", label: "Suriname", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "se", label: "Sweden", currency: "SEK", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ch", label: "Switzerland", currency: "CHF", marketRegion: "europe", primaryMarkets: ["SIX"] },
  { id: "sy", label: "Syria", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "tw", label: "Taiwan", currency: "TWD", marketRegion: "apac", primaryMarkets: ["TWSE"] },
  { id: "tj", label: "Tajikistan", currency: "USD", marketRegion: "apac", primaryMarkets: APAC },
  { id: "tz", label: "Tanzania", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "th", label: "Thailand", currency: "THB", marketRegion: "apac", primaryMarkets: ["SGX", "HKEX"] },
  { id: "tl", label: "Timor-Leste", currency: "USD", marketRegion: "apac", primaryMarkets: ["SGX"] },
  { id: "tg", label: "Togo", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "to", label: "Tonga", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "tt", label: "Trinidad and Tobago", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "tn", label: "Tunisia", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "tr", label: "Türkiye", currency: "TRY", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "tm", label: "Turkmenistan", currency: "USD", marketRegion: "apac", primaryMarkets: APAC },
  { id: "tv", label: "Tuvalu", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "ug", label: "Uganda", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ua", label: "Ukraine", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ae", label: "United Arab Emirates", currency: "AED", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "gb", label: "United Kingdom", currency: "GBP", marketRegion: "europe", primaryMarkets: ["LSE"] },
  { id: "us", label: "United States", currency: "USD", marketRegion: "americas", primaryMarkets: ["NASDAQ", "NYSE"] },
  { id: "uy", label: "Uruguay", currency: "USD", marketRegion: "americas", primaryMarkets: ["B3"] },
  { id: "uz", label: "Uzbekistan", currency: "USD", marketRegion: "apac", primaryMarkets: APAC },
  { id: "vu", label: "Vanuatu", currency: "AUD", marketRegion: "apac", primaryMarkets: ["ASX"] },
  { id: "va", label: "Vatican City", currency: "EUR", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "ve", label: "Venezuela", currency: "USD", marketRegion: "americas", primaryMarkets: AMERICAS },
  { id: "vn", label: "Vietnam", currency: "VND", marketRegion: "apac", primaryMarkets: ["SGX", "HKEX"] },
  { id: "ye", label: "Yemen", currency: "USD", marketRegion: "apac", primaryMarkets: ["TADAWUL"] },
  { id: "zm", label: "Zambia", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
  { id: "zw", label: "Zimbabwe", currency: "USD", marketRegion: "europe", primaryMarkets: EUROPE },
];
