import type { Competitor, StockProfile } from "./types";
import {
  CRYPTO_ASSET_TICKERS,
  getCryptoBrandColor,
  getCryptoDisplayName,
} from "./cryptoBrand";

type CryptoBaseProfile = Omit<StockProfile, "chartData" | "competitors"> & {
  competitorTickers: string[];
};

/**
 * Approximate reference profiles for Browse crypto.
 * Prices are static seeds (no crypto price API); UI still shows full crypto metrics.
 */
export const CRYPTO_BASE_PROFILES: Record<string, CryptoBaseProfile> = {
  BTC: {
    ticker: "BTC",
    name: "Bitcoin",
    price: 67240.5,
    change: 1240.2,
    changePercent: 1.88,
    logoColor: "#f7931a",
    marketCap: "$1.32T",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$28.4B",
    circulatingSupply: "19.8M BTC",
    totalSupply: "21M BTC",
    fdv: "$1.41T",
    allTimeHigh: "$73,750",
    allTimeLow: "$67.81",
    competitorTickers: ["ETH", "SOL", "COIN"],
  },
  ETH: {
    ticker: "ETH",
    name: "Ethereum",
    price: 3421.8,
    change: 72.4,
    changePercent: 2.16,
    logoColor: "#627eea",
    marketCap: "$411B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$14.2B",
    circulatingSupply: "120.4M ETH",
    totalSupply: "120.4M ETH",
    fdv: "$411B",
    allTimeHigh: "$4,878",
    allTimeLow: "$0.43",
    competitorTickers: ["BTC", "SOL", "COIN"],
  },
  SOL: {
    ticker: "SOL",
    name: "Solana",
    price: 148.2,
    change: 4.6,
    changePercent: 3.2,
    logoColor: "#9945ff",
    marketCap: "$72B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$3.1B",
    circulatingSupply: "486M SOL",
    totalSupply: "590M SOL",
    fdv: "$87B",
    allTimeHigh: "$260",
    allTimeLow: "$0.50",
    competitorTickers: ["ETH", "AVAX", "NEAR"],
  },
  BNB: {
    ticker: "BNB",
    name: "BNB",
    price: 612.4,
    change: 8.2,
    changePercent: 1.36,
    logoColor: "#f3ba2f",
    marketCap: "$89B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$1.6B",
    circulatingSupply: "145M BNB",
    totalSupply: "145M BNB",
    fdv: "$89B",
    allTimeHigh: "$793",
    allTimeLow: "$0.10",
    competitorTickers: ["ETH", "SOL", "XRP"],
  },
  XRP: {
    ticker: "XRP",
    name: "XRP",
    price: 0.62,
    change: 0.018,
    changePercent: 2.99,
    logoColor: "#0a74da",
    marketCap: "$35B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$1.9B",
    circulatingSupply: "56.4B XRP",
    totalSupply: "100B XRP",
    fdv: "$62B",
    allTimeHigh: "$3.84",
    allTimeLow: "$0.0028",
    competitorTickers: ["SOL", "ADA", "TRX"],
  },
  ADA: {
    ticker: "ADA",
    name: "Cardano",
    price: 0.68,
    change: 0.022,
    changePercent: 3.35,
    logoColor: "#0033ad",
    marketCap: "$24B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$720M",
    circulatingSupply: "35.3B ADA",
    totalSupply: "45B ADA",
    fdv: "$31B",
    allTimeHigh: "$3.10",
    allTimeLow: "$0.017",
    competitorTickers: ["SOL", "DOT", "ATOM"],
  },
  DOGE: {
    ticker: "DOGE",
    name: "Dogecoin",
    price: 0.16,
    change: 0.006,
    changePercent: 3.9,
    logoColor: "#c2a633",
    marketCap: "$23B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$1.1B",
    circulatingSupply: "146B DOGE",
    totalSupply: "146B DOGE",
    fdv: "$23B",
    allTimeHigh: "$0.74",
    allTimeLow: "$0.000085",
    competitorTickers: ["SHIB", "XRP", "SOL"],
  },
  AVAX: {
    ticker: "AVAX",
    name: "Avalanche",
    price: 28.4,
    change: 0.92,
    changePercent: 3.35,
    logoColor: "#e84142",
    marketCap: "$11.6B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$480M",
    circulatingSupply: "408M AVAX",
    totalSupply: "720M AVAX",
    fdv: "$20B",
    allTimeHigh: "$146",
    allTimeLow: "$2.80",
    competitorTickers: ["SOL", "NEAR", "DOT"],
  },
  DOT: {
    ticker: "DOT",
    name: "Polkadot",
    price: 6.42,
    change: 0.18,
    changePercent: 2.88,
    logoColor: "#e6007a",
    marketCap: "$9.8B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$260M",
    circulatingSupply: "1.53B DOT",
    totalSupply: "1.53B DOT",
    fdv: "$9.8B",
    allTimeHigh: "$55",
    allTimeLow: "$2.70",
    competitorTickers: ["ATOM", "ADA", "NEAR"],
  },
  LINK: {
    ticker: "LINK",
    name: "Chainlink",
    price: 14.8,
    change: 0.42,
    changePercent: 2.92,
    logoColor: "#375bd2",
    marketCap: "$9.2B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$410M",
    circulatingSupply: "626M LINK",
    totalSupply: "1B LINK",
    fdv: "$14.8B",
    allTimeHigh: "$52.88",
    allTimeLow: "$0.15",
    competitorTickers: ["ETH", "UNI", "DOT"],
  },
  MATIC: {
    ticker: "MATIC",
    name: "Polygon",
    price: 0.42,
    change: 0.012,
    changePercent: 2.94,
    logoColor: "#8247e5",
    marketCap: "$4.1B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$280M",
    circulatingSupply: "9.8B MATIC",
    totalSupply: "10B MATIC",
    fdv: "$4.2B",
    allTimeHigh: "$2.92",
    allTimeLow: "$0.003",
    competitorTickers: ["ARB", "SOL", "ETH"],
  },
  SHIB: {
    ticker: "SHIB",
    name: "Shiba Inu",
    price: 0.0000185,
    change: 0.0000006,
    changePercent: 3.35,
    logoColor: "#ffa409",
    marketCap: "$10.9B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$520M",
    circulatingSupply: "589T SHIB",
    totalSupply: "589T SHIB",
    fdv: "$10.9B",
    allTimeHigh: "$0.000088",
    allTimeLow: "$0.0000000005",
    competitorTickers: ["DOGE", "XRP", "SOL"],
  },
  LTC: {
    ticker: "LTC",
    name: "Litecoin",
    price: 86.4,
    change: 1.8,
    changePercent: 2.13,
    logoColor: "#345d9d",
    marketCap: "$6.5B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$380M",
    circulatingSupply: "75.1M LTC",
    totalSupply: "84M LTC",
    fdv: "$7.3B",
    allTimeHigh: "$410",
    allTimeLow: "$1.15",
    competitorTickers: ["BTC", "XRP", "DOGE"],
  },
  UNI: {
    ticker: "UNI",
    name: "Uniswap",
    price: 9.85,
    change: 0.28,
    changePercent: 2.93,
    logoColor: "#ff007a",
    marketCap: "$5.9B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$210M",
    circulatingSupply: "600M UNI",
    totalSupply: "1B UNI",
    fdv: "$9.9B",
    allTimeHigh: "$44.97",
    allTimeLow: "$0.42",
    competitorTickers: ["LINK", "ETH", "SOL"],
  },
  ATOM: {
    ticker: "ATOM",
    name: "Cosmos",
    price: 7.12,
    change: 0.2,
    changePercent: 2.89,
    logoColor: "#2e3148",
    marketCap: "$2.8B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$140M",
    circulatingSupply: "391M ATOM",
    totalSupply: "391M ATOM",
    fdv: "$2.8B",
    allTimeHigh: "$44.70",
    allTimeLow: "$1.16",
    competitorTickers: ["DOT", "NEAR", "ADA"],
  },
  TRX: {
    ticker: "TRX",
    name: "TRON",
    price: 0.16,
    change: 0.004,
    changePercent: 2.56,
    logoColor: "#ef0027",
    marketCap: "$13.8B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$520M",
    circulatingSupply: "86.5B TRX",
    totalSupply: "86.5B TRX",
    fdv: "$13.8B",
    allTimeHigh: "$0.23",
    allTimeLow: "$0.0011",
    competitorTickers: ["XRP", "SOL", "TON"],
  },
  TON: {
    ticker: "TON",
    name: "Toncoin",
    price: 5.42,
    change: 0.16,
    changePercent: 3.04,
    logoColor: "#0098ea",
    marketCap: "$13.6B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$240M",
    circulatingSupply: "2.5B TON",
    totalSupply: "5.1B TON",
    fdv: "$27.6B",
    allTimeHigh: "$8.25",
    allTimeLow: "$0.52",
    competitorTickers: ["SOL", "NEAR", "TRX"],
  },
  NEAR: {
    ticker: "NEAR",
    name: "NEAR Protocol",
    price: 5.18,
    change: 0.19,
    changePercent: 3.81,
    logoColor: "#00c08b",
    marketCap: "$5.8B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$320M",
    circulatingSupply: "1.12B NEAR",
    totalSupply: "1.2B NEAR",
    fdv: "$6.2B",
    allTimeHigh: "$20.42",
    allTimeLow: "$0.53",
    competitorTickers: ["SOL", "AVAX", "APT"],
  },
  APT: {
    ticker: "APT",
    name: "Aptos",
    price: 8.64,
    change: 0.26,
    changePercent: 3.1,
    logoColor: "#00bfff",
    marketCap: "$4.4B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$210M",
    circulatingSupply: "510M APT",
    totalSupply: "1.1B APT",
    fdv: "$9.5B",
    allTimeHigh: "$19.92",
    allTimeLow: "$3.08",
    competitorTickers: ["SOL", "NEAR", "AVAX"],
  },
  ARB: {
    ticker: "ARB",
    name: "Arbitrum",
    price: 0.72,
    change: 0.024,
    changePercent: 3.45,
    logoColor: "#28a0f0",
    marketCap: "$2.6B",
    revenue: "—",
    peRatio: "N/A",
    eps: "N/A",
    ebitda: "—",
    dividendYield: "—",
    volume24h: "$280M",
    circulatingSupply: "3.6B ARB",
    totalSupply: "10B ARB",
    fdv: "$7.2B",
    allTimeHigh: "$2.40",
    allTimeLow: "$0.40",
    competitorTickers: ["MATIC", "ETH", "SOL"],
  },
};

export function getCryptoBaseProfile(
  ticker: string
): CryptoBaseProfile | null {
  return CRYPTO_BASE_PROFILES[ticker.toUpperCase()] ?? null;
}

export function buildCryptoCompetitor(
  ticker: string,
  fallbackPrice = 100
): Competitor {
  const upper = ticker.toUpperCase();
  const profile = CRYPTO_BASE_PROFILES[upper];
  if (profile) {
    return {
      ticker: upper,
      name: profile.name,
      price: profile.price,
      changePercent: profile.changePercent,
      color: profile.logoColor,
    };
  }

  const EQUITY_PEERS: Record<
    string,
    Pick<Competitor, "name" | "price" | "changePercent" | "color">
  > = {
    COIN: {
      name: "Coinbase Global",
      price: 245.6,
      changePercent: 1.4,
      color: "#0052ff",
    },
    MSTR: {
      name: "MicroStrategy",
      price: 1680.2,
      changePercent: 3.2,
      color: "#d9232e",
    },
  };

  if (EQUITY_PEERS[upper]) {
    return { ticker: upper, ...EQUITY_PEERS[upper] };
  }

  return {
    ticker: upper,
    name: getCryptoDisplayName(upper),
    price: fallbackPrice,
    changePercent: 1.2,
    color: getCryptoBrandColor(upper),
  };
}

export function listSeededCryptoTickers(): string[] {
  return [...CRYPTO_ASSET_TICKERS];
}
